### ISSUE TITLE
Does not work on 1.2.17.. 

### ISSUE THREAD

**Issue by snowyurik** [mantisbt-plugins/AdminSetPassword#1]
I see the tip about 1.2.14, but will you create new version for 1.2.17 or i'll better start my own plugin of that kind?

**Comment by langerheiko** [comment]
Do you have any problems with that plugin on 1.2.17? Please let me know.

**Comment by snowyurik** [comment]
Well, finally i found it. But i can't change my own pw this way and i can't set up password for new user during creation.

To see any changes i should:
1. Create new user
2. Edit this user

and if you suppose to edit Administrator's account (from "manage users" page) you do not see the form for changing password. That makes me think that plugin just don't work.

**Comment by langerheiko** [comment]
You cannot change your own password that way, because the field that I use to attach the new form field is not there.
If you want to create a password upon creation of a new user, you will have to do a setting in config_inc.php ($g_allow_signup = OFF).

**Comment by bueltge** [comment]
We should close this issue, no longer necessary or helpful.
