### ISSUE TITLE
password field does not appear

### ISSUE THREAD

**Issue by philstra** [mantisbt-plugins/AdminSetPassword#5]
I installed Admin Set Password 1.0.0 in Mantis 2.22.0, but the password field does not appear on manage_user_edit_page.php. The javascript code is loaded, but both Chrome and Firefox have similar complaints: 
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”)

**Comment by dregad** [comment]
Please see https://github.com/mantisbt-plugins/AdminSetPassword/pull/2#issuecomment-570932990. 

Until @bueltge (or some other good soul willing to do the required adaptations) has the time to address the issues in PR #2 this plugin is effectively not working with MantisBT 2.0, unless you disable CSP (which I would not recommend, for obvious security reasons).
